sudo: false
language: python
python:
  - "2.7"
cache: pip
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry pip install codecov
  - pip install -e .
script:
  - py.test --cov=webhookdb
  - cd docs && make html
  - cd ..
after_success:
  - codecov
branches:
    only:
      - master
